### ISSUE TITLE
Descriptor calculation problem: unable to apply for new dataset

### ISSUE THREAD

**Issue by M-asaki-K** [yoshida-lab/XenonPy#190] opened 2020-04-29 03:14 UTC
Hi,
Following the tutorial (compositional descriptors calculation for sample dataset, which normally worked), I tried to apply the calculation for another dataset I collected from Materials Project. Unfortunately, the results are all "NaN"s. 
I'd be appreciated to know if there're some tips to do same calculation for new dataset.
[sample data](https://github.com/M-asaki-K/XenonPy-study/blob/master/MPcompwithcomposition.csv)

**Comment by TsumiNa** [comment] 2020-05-10 06:40
@M-asaki-K Hi! Could you please show me your codes, which can let us reproduce your error.

**Comment by M-asaki-K** [comment] 2020-05-10 07:00
Thank you very much for your reply! Here's the sample codes I used.
[sample codes](https://github.com/M-asaki-K/XenonPy-study/blob/master/Xenonpy_compositiondescriptor_tutorial_and_test.ipynb)

**Comment by TsumiNa** [comment] 2020-05-10 07:49
@M-asaki-K The date type of `composition` is incorrect. The acceptable data types is `dict` or `pymatgen.core.composition.PMGComp`. Because the **CSV** format is designed to store table-based information, Any information such as `dict` will be transformed into `str`.

**Comment by M-asaki-K** [comment] 2020-05-10 07:59
Thank you very much for your kind information!

**Comment by TsumiNa** [comment] 2020-05-10 08:50
@M-asaki-K I'd like to close this issue. If you still have questions, feel free to reopen this.

**Closed by TsumiNa** 2020-05-10 08:50 UTC
